# Virtualbox setup

- name: Install build-esential and dkms (prepare)
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - build-essential
    - dkms
    - unzip

- name: Add VirtualBox repo keys
  apt_key:
    url: "https://www.virtualbox.org/download/{{ item }}.asc"
    state: present
  with_items:
    - oracle_vbox
    - oracle_vbox_2016

- name: Add VirtualBox repo
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state: present
    update_cache: yes

- name: Install virtualbox in given version
  apt:
    name: virtualbox-{{ virtualbox_version }}
    state: present

- name: Check if extension pack is already installed
  shell: "VBoxManage list extpacks"
  register: extpack_list

- name: Download VirtualBox extension pack
  get_url:
    url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}.2/Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.2.vbox-extpack"
    dest: /tmp/oracle_virtualbox_extension_pack.vbox-extpack
    force: yes
  register: download_result
  when: extpack_list.stdout == "Extension Packs: 0"

- name: Install VirtualBox extension pack
  shell: "VBoxManage extpack install --replace /tmp/oracle_virtualbox_extension_pack.vbox-extpack"
  when: extpack_list.stdout == "Extension Packs: 0"

- name: Add user to run virtualbox deamon
  user:
    name: "{{ virtualbox_user }}"
    createhome: yes
    shell: '/bin/bash'
    state: present
    append: yes # append groups
    groups: vboxusers
    update_password: on_create # only touch PW on user creation
    password: "{{ virtualbox_user_sha_pw }}"

- name: Create a folder for ISO files to be shared with phpVirtualBox
  file:
    path: /home/{{virtualbox_user}}/isos
    owner: "{{ virtualbox_user }}"
    group: vboxusers
    mode: 0770
    state: directory

